---
- name: Deploy OpenShift on OpenShift Virtualization
  become: false
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Create Namespace
      kubernetes.core.k8s:
        api_key: "{{ virtualization_token }}"
        host: "{{ virtualization_api }}"
        resource_definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ infra_env.namespace }}"
          spec: {}
        state: present
        validate_certs: "{{ validate_certs }}"

    - name: Create Virtual Machines
      vars:
        k8s_auth_api_key: "{{ virtualization_token }}"
        k8s_auth_host: "{{ virtualization_api }}"
      ansible.builtin.include_role:
        name: o3_create_vms

    - name: Create InfraEnv
      vars:
        k8s_auth_api_key: "{{ hub_token }}"
        k8s_auth_host: "{{ hub_api }}"
      ansible.builtin.include_role:
        name: o3_acm_create_infraenv
      when:
        - infra_env.create | default(false)

    - name: Attach Discovery ISO and Boot Virtual Machines
      vars:
        k8s_auth_api_key: "{{ virtualization_token }}"
        k8s_auth_host: "{{ virtualization_api }}"
      ansible.builtin.include_role:
        name: o3_first_boot

    - name: Wait for Agents
      vars:
        k8s_auth_api_key: "{{ hub_token }}"
        k8s_auth_host: "{{ hub_api }}"
      ansible.builtin.include_role:
        name: o3_acm_agent
        tasks_from: wait

    - name: Approve Agents
      vars:
        k8s_auth_api_key: "{{ hub_token }}"
        k8s_auth_host: "{{ hub_api }}"
      ansible.builtin.include_role:
        name: o3_acm_agent
        tasks_from: approve

    - name: Create Draft Cluster
      vars:
        k8s_auth_api_key: "{{ hub_token }}"
        k8s_auth_host: "{{ hub_api }}"
      ansible.builtin.include_role:
        name: o3_acm_draft_cluster

    - name: Bind Agents to Cluster
      vars:
        k8s_auth_api_key: "{{ hub_token }}"
        k8s_auth_host: "{{ hub_api }}"
      ansible.builtin.include_role:
        name: o3_acm_agent
        tasks_from: bind

    - name: Configure Agents
      vars:
        k8s_auth_api_key: "{{ hub_token }}"
        k8s_auth_host: "{{ hub_api }}"
      ansible.builtin.include_role:
        name: o3_acm_agent
        tasks_from: configure

    - name: Wait for Install Ready
      vars:
        k8s_auth_api_key: "{{ hub_token }}"
        k8s_auth_host: "{{ hub_api }}"
      ansible.builtin.include_role:
        name: o3_acm_wait_for
        tasks_from: install-ready

    - name: Initiate Cluster Installation
      kubernetes.core.k8s:
        api_key: "{{ hub_token }}"
        host: "{{ hub_api }}"
        resource_definition:
          apiVersion: extensions.hive.openshift.io/v1beta1
          kind: AgentClusterInstall
          metadata:
            name: "{{ acm.cluster_name }}"
            namespace: "{{ infra_env.namespace }}"
          spec:
            holdInstallation: false
        state: patched
        validate_certs: "{{ validate_certs }}"

    - name: Wait for Install Completed
      vars:
        k8s_auth_api_key: "{{ hub_token }}"
        k8s_auth_host: "{{ hub_api }}"
      ansible.builtin.include_role:
        name: o3_acm_wait_for
        tasks_from: install-complete

    - name: Subscribe Cluster
      vars:
        k8s_auth_api_key: "{{ hub_token }}"
        k8s_auth_host: "{{ hub_api }}"
      ansible.builtin.include_role:
        name: console_dot
        tasks_from: subscribe
      when:
        - openshift_subscription is defined
        - openshift_subscription.subscribe | default(false)
