---
- name: Wait for Agents
  block:
    - name: Query Agents
      kubernetes.core.k8s_info:
        api_key: "{{ k8s_auth_api_key }}"
        api_version: agent-install.openshift.io/v1beta1
        host: "{{ k8s_auth_host }}"
        kind: Agent
        label_selectors:
          - "infraenvs.agent-install.openshift.io = {{ infra_env.name }}"
        namespace: "{{ infra_env.namespace }}"
        validate_certs: "{{ validate_certs }}"
      register: agent_results

    - name: Reset _agent_shortnames
      ansible.builtin.set_fact:
        _agent_shortnames: []

    - name: Build List of Short Names from Agents
      ansible.builtin.set_fact:
        _agent_shortnames: >-
          {{
            _agent_shortnames +
            [
              item.status.inventory.hostname | split('.') | first
            ]
          }}
      loop: "{{ agent_results.resources }}"
      no_log: true
      when:
        - item.status is defined
        - item.status.inventory is defined
        - item.status.inventory.hostname is defined

    - name: Check for Missing Agents
      ansible.builtin.assert:
        that:
          - groups[provision_group] | difference(_agent_shortnames) | length == 0
  rescue:
    - name: Verify Failed Task
      ansible.builtin.fail:
        msg: "An unexpected task in the task block failed."
      when:
        - ansible_failed_task.name != "Check for Missing Agents"

    - name: Missing the Following Agents
      ansible.builtin.debug:
        msg: "{{ groups[provision_group] | difference(_agent_shortnames) }}"

    - name: Wait for Additional Agents to Populate
      ansible.builtin.wait_for:
        timeout: "{{ agent_discovery_wait_seconds }}"

    - name: Retry
      ansible.builtin.include_tasks:
        file: wait.yaml
